### ISSUE TITLE
Cursor timeouts

### ISSUE THREAD

**Issue by seivan** [OpenKitten/MongoKitten#42]
I get hit with this 
`
fatal error: Error fetching extra data from the server in MongoKitten.Cursor<heroku_6pxt0cxh.browseitems> with error: timeout: file /tmp/build_0e4a544672ea566050f30beb848fe070/Packages/MongoKitten-1.7.0/Sources/MongoKitten/Cursor.swift, line 79
`

Doesn't matter, happens on both read and writes.

I suspect it's related to https://jira.mongodb.org/browse/SERVER-8188

Any takes?

**Comment by Joannis** [comment]
Are you storing this cursor for use after 10+ minutes? If that's the case, then yes, that should be happening. Otherwise I'll need to investigate into this.

**Comment by seivan** [comment]
I'm assuming after the request it would go away on its own. Not storing anything.

**Comment by Joannis** [comment]
It should.. Let me check into it more deeply. Does this error occur often?

**Comment by seivan** [comment]
Once it occurs (Heroku btw) it stays until I restart dynos.

**Comment by Joannis** [comment]
We have confirmed your bug today in our own environment. Sadly it was build on release mode when it happened and we didn't manage to extract any data from it except for MongoKitten throwing a timeout. The cause is still unknown although I expect we'll solve it in the next days with our new connection system in the works.

We did however not need to reboot our application in our environment using MongoKitten 1.7. The problem occurred only once total and didn't affect MongoKitten requests following it up.

**Comment by seivan** [comment]
@Joannis Well, I am assuming I got limited connections and the Dyno keeps a reference to them until it goes to sleep. 
I feel like they should die once the query is complete and the context falls out. I am *guessing* there might be a memory leak. I'll dig some more. 👍

**Comment by Obbut** [comment]
I solved this on the mongokitten2 branch.

**Comment by Joannis** [comment]
We'll issue another patch soon. It'll also be tagged `0.0.5`, so you'll have to re-fetch the MongoKitten dependency. This fixes all unexpected timeouts. It affects 1/512 Documents due to an error in the socket library we're using by default, which might also be a Document you have.

**Comment by Joannis** [comment]
@seivan is your issue solved with 0.0.5?

**Comment by seivan** [comment]
I will try it this weekend. I’m using Vapor and Swift packages if that makes any difference.

**Comment by Joannis** [comment]
Have you experienced additional issues last weekend?

**Comment by seivan** [comment]
I haven't had a chance unfortunately. You guys haven't experienced it again on Heroku?

**Comment by Joannis** [comment]
We're not using heroku, so I can't tell you that. We have experienced the issue in other environments which have been solved for us.

**Comment by seivan** [comment]
@Joannis Still happens here.
fatal error: Error fetching extra data from the server in MongoKitten.Cursor<heroku_6pxt0cxh.browseitems> with error: timeout: file /tmp/build_71afc0cce7aa23eb54df22e1d65f59c7/Packages/MongoKitten-1.7.0/Sources/MongoKitten/Cursor.swift, line 79

**Comment by Joannis** [comment]
Can you provide some more details about your request and expected response?

**Comment by seivan** [comment]
This is just fetching the entire collection without any predicates or queries. If you have an email I could invite you to an isolated sample on Heroku.

**Comment by Joannis** [comment]
@seivan I looked back at your last error report and it reports 1.7.0 being used. We fixed the bug in 1.7.1 and 2.0.0.
